services:
  - type: web
    name: face-confirmation
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 120 app:app
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_xXbEUf0y1Gir@ep-old-glitter-a4sg9zar-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require
        generateValue: true
      - key: FLASK_DEBUG
        value: false
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "3"
      - key: OPENCV_LOG_LEVEL
        value: "ERROR"
      - key: CUDA_VISIBLE_DEVICES
        value: "-1"
